llm_config:
  model: "gemini/gemini-pro"
host_config:
  host: "0.0.0.0"
  port: 8000
sources:
  - google_drive_folder:
    kind: gdrive
    config:
      object_id: "GDrive folder/file object id" # folder used in the managed demo
      service_user_credentials_file: ./credentials.json
      refresh_interval: 5
  
